name: Manifest Validation

on:
  workflow_call:
    inputs:
      kustomize_build_dir:
        required: true
        type: string

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: 'Kustomize Build'
        uses: karancode/kustomize-github-action@master
        with:
          kustomize_version: '4.4.0'
          kustomize_build_dir: ${{ inputs.kustomize_build_dir }}
          kustomize_comment: true
          kustomize_output_file: "build.yaml"

      - name: login to Github Packages
        run: echo ${{ github.token }} | docker login https://ghcr.io -u ${GITHUB_ACTOR} --password-stdin

      - name: kubeconform
        uses: docker://ghcr.io/yannh/kubeconform:master
        with:
          entrypoint: '/kubeconform'
          args: "-ignore-missing-schemas -ignore-filename-pattern ^. -summary -output json ./"

      - name: checkout conftest policies
        uses: actions/checkout@v2
        with:
          repository: BloomerAB/sas.kubility.reusable-workflows
          path: sas.kubility.reusable-workflows

      - name: conftest
        uses: stefanprodan/kube-tools@v1
        with:
          conftest: 0.28.3
          command: |
            mv sas.kubility.reusable-workflows/conftest/kubernetes/workloads ./policy && rm -rf sas.kubility.reusable-workflows
            conftest test --all-namespaces -o table build.yaml
